// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pbl3.DataAccess.Data;

#nullable disable

namespace Pbl3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530061826_FixSeatRelation_FlightSeat")]
    partial class FixSeatRelation_FlightSeat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Booking", b =>
                {
                    b.Property<string>("codeBooking")
                        .HasColumnType("varchar(8)");

                    b.Property<decimal>("bookedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("bookedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("codeTransaction")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("idUser")
                        .HasColumnType("int");

                    b.HasKey("codeBooking");

                    b.HasIndex("codeTransaction")
                        .IsUnique();

                    b.HasIndex("idUser");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Ticket", b =>
                {
                    b.Property<string>("codeTicket")
                        .HasColumnType("varchar(16)");

                    b.Property<bool>("CanSelectSeat")
                        .HasColumnType("bit");

                    b.Property<string>("codeBooking")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("codeFlight")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("codeSeat")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<DateOnly>("dateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("departureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("departureTime")
                        .HasColumnType("time");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("identityCard")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("passengerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codeTicket");

                    b.HasIndex("codeBooking");

                    b.HasIndex("codeFlight", "departureDate", "departureTime");

                    b.HasIndex("codeSeat", "codeFlight", "departureDate", "departureTime")
                        .IsUnique();

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.DiscountFlight", b =>
                {
                    b.Property<string>("codeFlight")
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("departureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("departureTime")
                        .HasColumnType("time");

                    b.Property<int>("discountPercentage")
                        .HasColumnType("int");

                    b.HasKey("codeFlight", "departureDate", "departureTime");

                    b.ToTable("DiscountFlight");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.Flight", b =>
                {
                    b.Property<string>("codeFlight")
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("departureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("departureTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("landingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("landingTime")
                        .HasColumnType("time");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codeFlight", "departureDate", "departureTime");

                    b.HasIndex("codeFlight")
                        .IsUnique();

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.FlightSeat", b =>
                {
                    b.Property<string>("codeSeat")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("codeFlight")
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("departureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("departureTime")
                        .HasColumnType("time");

                    b.Property<bool>("isBooked")
                        .HasColumnType("bit");

                    b.Property<string>("ticketcodeTicket")
                        .HasColumnType("varchar(16)");

                    b.HasKey("codeSeat", "codeFlight", "departureDate", "departureTime");

                    b.HasIndex("ticketcodeTicket");

                    b.HasIndex("codeFlight", "departureDate", "departureTime");

                    b.ToTable("FlightSeat");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.Seat", b =>
                {
                    b.Property<string>("codeSeat")
                        .HasColumnType("varchar(3)");

                    b.Property<int?>("codeType")
                        .HasColumnType("int");

                    b.HasKey("codeSeat");

                    b.HasIndex("codeType");

                    b.ToTable("Seat");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.TicketType", b =>
                {
                    b.Property<int>("codeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codeType"));

                    b.Property<bool>("canBeCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("canBeUpgrade")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("priceBooked")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("weightBaggage")
                        .HasColumnType("int");

                    b.HasKey("codeType");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("TicketType");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.Baggage", b =>
                {
                    b.Property<string>("codeBaggage")
                        .HasColumnType("varchar(19)");

                    b.Property<string>("codeTicket")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("codeTransaction")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("codeBaggage");

                    b.HasIndex("codeTicket");

                    b.HasIndex("codeTransaction")
                        .IsUnique();

                    b.ToTable("Baggage");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.City", b =>
                {
                    b.Property<string>("abbreviatedName")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("airplane")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("abbreviatedName");

                    b.HasIndex("airplane")
                        .IsUnique();

                    b.ToTable("City");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.FromTo", b =>
                {
                    b.Property<string>("codeFlight")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<float>("length")
                        .HasColumnType("real");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("codeFlight");

                    b.HasIndex("from");

                    b.HasIndex("to");

                    b.ToTable("FromTo");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.Request", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("requester_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("reviewed_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("reviewer_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("requester_id");

                    b.HasIndex("reviewer_id");

                    b.ToTable("Request");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Payment.Transaction", b =>
                {
                    b.Property<string>("codeTransaction")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("beneficiaryAccount")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("beneficiaryBank")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("sourceAccount")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("sourceBank")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("timeTransaction")
                        .HasColumnType("datetime2");

                    b.Property<int>("transactionAmount")
                        .HasColumnType("int");

                    b.HasKey("codeTransaction");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Promotions.Promotion", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("codeFlight")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("departureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("departureTime")
                        .HasColumnType("time");

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("codeFlight", "departureDate", "departureTime")
                        .IsUnique();

                    b.ToTable("Promotion");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.User", b =>
                {
                    b.Property<int>("id")
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("dateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("name")
                        .IsUnique();

                    b.HasIndex("phoneNumber")
                        .IsUnique();

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.CancelRequest", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Others.Request");

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.Property<string>("codeTicket")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("Userid");

                    b.HasIndex("codeTicket")
                        .IsUnique()
                        .HasFilter("[codeTicket] IS NOT NULL");

                    b.ToTable("CancelRequest");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.FlightRequest", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Others.Request");

                    b.Property<string>("codeFlight")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("departureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("departureTime")
                        .HasColumnType("time");

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.HasIndex("codeFlight", "departureDate", "departureTime");

                    b.ToTable("FlightRequest");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Promotions.PromotionCancelRequest", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Others.Request");

                    b.Property<string>("promotion_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("promotion_id")
                        .IsUnique()
                        .HasFilter("[promotion_id] IS NOT NULL");

                    b.ToTable("PromotionCancelRequest");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Promotions.PromotionRequest", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Others.Request");

                    b.Property<string>("codeFlight")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("departureDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("departureTime")
                        .HasColumnType("time");

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("codeFlight", "departureDate", "departureTime")
                        .IsUnique()
                        .HasFilter("[codeFlight] IS NOT NULL AND [departureDate] IS NOT NULL AND [departureTime] IS NOT NULL");

                    b.ToTable("PromotionRequest");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.StaffRequest", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Others.Request");

                    b.Property<string>("address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.ToTable("StaffRequest");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Admin", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Users.User");

                    b.Property<DateOnly>("joinedDate")
                        .HasColumnType("date");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Passenger", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Users.User");

                    b.Property<int>("pointReward")
                        .HasColumnType("int");

                    b.ToTable("Passenger");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Staff", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Users.User");

                    b.Property<DateOnly>("joinedDate")
                        .HasColumnType("date");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Booking", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Payment.Transaction", "transaction")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Bookings.Booking", "codeTransaction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Users.User", "user")
                        .WithMany("bookings")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("transaction");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Ticket", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Bookings.Booking", "booking")
                        .WithMany("tickets")
                        .HasForeignKey("codeBooking")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Flights.Flight", "flight")
                        .WithMany("tickets")
                        .HasForeignKey("codeFlight", "departureDate", "departureTime")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Flights.FlightSeat", "seat")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Bookings.Ticket", "codeSeat", "codeFlight", "departureDate", "departureTime")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("booking");

                    b.Navigation("flight");

                    b.Navigation("seat");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.DiscountFlight", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Flights.Flight", "flight")
                        .WithOne("discountFlight")
                        .HasForeignKey("Pbl3.DataAccess.Models.Flights.DiscountFlight", "codeFlight", "departureDate", "departureTime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flight");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.Flight", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Others.FromTo", "fromTo")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Flights.Flight", "codeFlight")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("fromTo");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.FlightSeat", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Flights.Seat", "seat")
                        .WithMany()
                        .HasForeignKey("codeSeat")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Bookings.Ticket", "ticket")
                        .WithMany()
                        .HasForeignKey("ticketcodeTicket");

                    b.HasOne("Pbl3.DataAccess.Models.Flights.Flight", "flight")
                        .WithMany("flightSeats")
                        .HasForeignKey("codeFlight", "departureDate", "departureTime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flight");

                    b.Navigation("seat");

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.Seat", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Flights.TicketType", "type")
                        .WithMany()
                        .HasForeignKey("codeType")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("type");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.Baggage", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Bookings.Ticket", "ticket")
                        .WithMany("baggages")
                        .HasForeignKey("codeTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Payment.Transaction", "transaction")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Others.Baggage", "codeTransaction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ticket");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.FromTo", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Others.City", "fromCity")
                        .WithMany()
                        .HasForeignKey("from")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Others.City", "toCity")
                        .WithMany()
                        .HasForeignKey("to")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("fromCity");

                    b.Navigation("toCity");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.Request", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Users.User", "requester")
                        .WithMany("requests")
                        .HasForeignKey("requester_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Pbl3.DataAccess.Models.Users.Admin", "reviewer")
                        .WithMany("solved")
                        .HasForeignKey("reviewer_id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("requester");

                    b.Navigation("reviewer");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Promotions.Promotion", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Flights.Flight", "flight")
                        .WithOne("promotion")
                        .HasForeignKey("Pbl3.DataAccess.Models.Promotions.Promotion", "codeFlight", "departureDate", "departureTime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flight");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.CancelRequest", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Users.User", null)
                        .WithMany("cancelRequests")
                        .HasForeignKey("Userid");

                    b.HasOne("Pbl3.DataAccess.Models.Bookings.Ticket", "ticket")
                        .WithOne("request")
                        .HasForeignKey("Pbl3.DataAccess.Models.Bookings.CancelRequest", "codeTicket")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Others.Request", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Bookings.CancelRequest", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.FlightRequest", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Others.Request", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Flights.FlightRequest", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Flights.Flight", "flight")
                        .WithMany("requests")
                        .HasForeignKey("codeFlight", "departureDate", "departureTime")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("flight");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Promotions.PromotionCancelRequest", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Others.Request", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Promotions.PromotionCancelRequest", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Promotions.Promotion", "promotion")
                        .WithOne("cancelRequest")
                        .HasForeignKey("Pbl3.DataAccess.Models.Promotions.PromotionCancelRequest", "promotion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("promotion");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Promotions.PromotionRequest", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Others.Request", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Promotions.PromotionRequest", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Flights.Flight", "flight")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Promotions.PromotionRequest", "codeFlight", "departureDate", "departureTime")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("flight");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.StaffRequest", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Others.Request", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Users.StaffRequest", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Admin", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Users.Admin", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Passenger", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Users.Passenger", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Staff", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Users.Staff", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Booking", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Ticket", b =>
                {
                    b.Navigation("baggages");

                    b.Navigation("request")
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.Flight", b =>
                {
                    b.Navigation("discountFlight")
                        .IsRequired();

                    b.Navigation("flightSeats");

                    b.Navigation("promotion")
                        .IsRequired();

                    b.Navigation("requests");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Promotions.Promotion", b =>
                {
                    b.Navigation("cancelRequest")
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.User", b =>
                {
                    b.Navigation("bookings");

                    b.Navigation("cancelRequests");

                    b.Navigation("requests");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Admin", b =>
                {
                    b.Navigation("solved");
                });
#pragma warning restore 612, 618
        }
    }
}
