// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pbl3.DataAccess.Data;

#nullable disable

namespace Pbl3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417192140_UpdateUser")]
    partial class UpdateUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Booking", b =>
                {
                    b.Property<string>("codeBooking")
                        .HasColumnType("varchar(8)");

                    b.Property<int>("bookedPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("bookedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("codeTransaction")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("idUser")
                        .HasColumnType("int");

                    b.HasKey("codeBooking");

                    b.HasIndex("codeTransaction")
                        .IsUnique();

                    b.HasIndex("idUser");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Ticket", b =>
                {
                    b.Property<string>("codeTicket")
                        .HasColumnType("varchar(6)");

                    b.Property<bool>("CanSelectSeat")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("arriveDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("arriveTime")
                        .HasColumnType("time");

                    b.Property<string>("codeBooking")
                        .IsRequired()
                        .HasColumnType("varchar(8)");

                    b.Property<string>("codeFlight")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("codeSeat")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("identityCard")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("codeTicket");

                    b.HasIndex("codeBooking");

                    b.HasIndex("codeFlight", "arriveDate", "arriveTime");

                    b.HasIndex("codeSeat", "codeFlight", "arriveDate", "arriveTime")
                        .IsUnique();

                    b.ToTable("Ticket");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.Flight", b =>
                {
                    b.Property<string>("codeFlight")
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("arriveDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("arriveTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("landingDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("landingTime")
                        .HasColumnType("time");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("codeFlight", "arriveDate", "arriveTime");

                    b.HasIndex("codeFlight")
                        .IsUnique();

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.FlightSeat", b =>
                {
                    b.Property<string>("codeSeat")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("codeFlight")
                        .HasColumnType("varchar(6)");

                    b.Property<DateOnly>("arriveDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("arriveTime")
                        .HasColumnType("time");

                    b.Property<int>("codeType")
                        .HasColumnType("int");

                    b.Property<bool>("isBooked")
                        .HasColumnType("bit");

                    b.Property<string>("ticketcodeTicket")
                        .HasColumnType("varchar(6)");

                    b.HasKey("codeSeat", "codeFlight", "arriveDate", "arriveTime");

                    b.HasIndex("codeType")
                        .IsUnique();

                    b.HasIndex("ticketcodeTicket");

                    b.HasIndex("codeFlight", "arriveDate", "arriveTime");

                    b.ToTable("FlightSeat");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.TicketType", b =>
                {
                    b.Property<int>("codeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codeType"));

                    b.Property<bool>("canBeCanceled")
                        .HasColumnType("bit");

                    b.Property<bool>("canBeUpgrade")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("priceBooked")
                        .HasColumnType("int");

                    b.Property<int>("weightBaggage")
                        .HasColumnType("int");

                    b.HasKey("codeType");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("TicketType");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.Baggage", b =>
                {
                    b.Property<string>("codeTicket")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("codeTransaction")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("weight")
                        .HasColumnType("int");

                    b.HasKey("codeTicket", "codeTransaction");

                    b.HasIndex("codeTransaction")
                        .IsUnique();

                    b.ToTable("Baggage");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.City", b =>
                {
                    b.Property<string>("abbreviatedName")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("airplane")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("abbreviatedName");

                    b.HasIndex("airplane")
                        .IsUnique();

                    b.HasIndex("fullName")
                        .IsUnique();

                    b.ToTable("City");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.FromTo", b =>
                {
                    b.Property<string>("codeFlight")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("from")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("to")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("codeFlight");

                    b.HasIndex("from");

                    b.HasIndex("to");

                    b.ToTable("FromTo");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Payment.Transaction", b =>
                {
                    b.Property<string>("codeTransaction")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("beneficiaryAccount")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("beneficiaryBank")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("sourceAccount")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("sourceBank")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("timeTransaction")
                        .HasColumnType("datetime2");

                    b.Property<int>("transactionAmount")
                        .HasColumnType("int");

                    b.HasKey("codeTransaction");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("dateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(254)");

                    b.Property<int>("gender")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("name")
                        .IsUnique();

                    b.HasIndex("phoneNumber")
                        .IsUnique();

                    b.ToTable("User");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Admin", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Users.User");

                    b.Property<DateOnly>("joinedDate")
                        .HasColumnType("date");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Passenger", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Users.User");

                    b.Property<int>("pointReward")
                        .HasColumnType("int");

                    b.ToTable("Passenger");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Staff", b =>
                {
                    b.HasBaseType("Pbl3.DataAccess.Models.Users.User");

                    b.Property<DateOnly>("joinedDate")
                        .HasColumnType("date");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Booking", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Payment.Transaction", "transaction")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Bookings.Booking", "codeTransaction")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Users.User", "user")
                        .WithMany("bookings")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("transaction");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Ticket", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Bookings.Booking", "booking")
                        .WithMany("tickets")
                        .HasForeignKey("codeBooking")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Flights.Flight", "flight")
                        .WithMany("tickets")
                        .HasForeignKey("codeFlight", "arriveDate", "arriveTime")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Flights.FlightSeat", "seat")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Bookings.Ticket", "codeSeat", "codeFlight", "arriveDate", "arriveTime")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("booking");

                    b.Navigation("flight");

                    b.Navigation("seat");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.Flight", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Others.FromTo", "fromTo")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Flights.Flight", "codeFlight")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fromTo");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.FlightSeat", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Flights.TicketType", "type")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Flights.FlightSeat", "codeType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Bookings.Ticket", "ticket")
                        .WithMany()
                        .HasForeignKey("ticketcodeTicket");

                    b.HasOne("Pbl3.DataAccess.Models.Flights.Flight", "flight")
                        .WithMany("flightSeats")
                        .HasForeignKey("codeFlight", "arriveDate", "arriveTime")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("flight");

                    b.Navigation("ticket");

                    b.Navigation("type");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.Baggage", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Bookings.Ticket", "ticket")
                        .WithMany("baggages")
                        .HasForeignKey("codeTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Payment.Transaction", "transaction")
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Others.Baggage", "codeTransaction")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ticket");

                    b.Navigation("transaction");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Others.FromTo", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Others.City", "fromCity")
                        .WithMany()
                        .HasForeignKey("from")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Pbl3.DataAccess.Models.Others.City", "toCity")
                        .WithMany()
                        .HasForeignKey("to")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("fromCity");

                    b.Navigation("toCity");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Admin", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Users.Admin", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Passenger", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Users.Passenger", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.Staff", b =>
                {
                    b.HasOne("Pbl3.DataAccess.Models.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Pbl3.DataAccess.Models.Users.Staff", "id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Booking", b =>
                {
                    b.Navigation("tickets");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Bookings.Ticket", b =>
                {
                    b.Navigation("baggages");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Flights.Flight", b =>
                {
                    b.Navigation("flightSeats");

                    b.Navigation("tickets");
                });

            modelBuilder.Entity("Pbl3.DataAccess.Models.Users.User", b =>
                {
                    b.Navigation("bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
