import type {
  User,
  Flight,
  Ticket,
  ApprovalRequest,
  Destination,
  RevenueData,
  FlightPopularity,
} from "./types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "john@example.com",
    name: "John Smith",
    phone: "+1 234 567 8900",
    role: "customer",
    status: "active",
    createdAt: "2024-01-15",
  },
  {
    id: "user-2",
    email: "sarah@skyline.com",
    name: "Sarah Johnson",
    gender: "Female",
    address: "123 Main Street, New York",
    nationalId: "079203001234",
    dateOfBirth: "1998-05-12",
    phone: "+1 234 567 8901",
    role: "employee",
    status: "active",
    createdAt: "2023-06-01",
  },
  {
    id: "user-3",
    email: "michael@skyline.com",
    name: "Michael Chen",
    phone: "+1 234 567 8902",
    role: "manager",
    status: "active",
    createdAt: "2022-01-01",
  },
  {
    id: "user-4",
    email: "emma@example.com",
    name: "Emma Wilson",
    phone: "+1 234 567 8903",
    role: "customer",
    status: "active",
    createdAt: "2024-02-20",
  },
  {
    id: "user-5",
    email: "david@skyline.com",
    name: "David Brown",
    gender: "Male",
    address: "456 Oak Avenue, Chicago",
    nationalId: "079203009876",
    dateOfBirth: "1996-11-20",
    phone: "+1 234 567 8904",
    role: "employee",
    status: "pending",
    createdAt: "2024-03-01",
  },
];

// Mock Flights
export const mockFlights: Flight[] = [
  {
    id: "flight-1",
    flightNumber: "SL-101",
    airline: "SkyLine Airways",
    departure: {
      city: "New York",
      airport: "John F. Kennedy International",
      code: "JFK",
      time: "08:00",
      date: "2024-04-15",
    },
    arrival: {
      city: "London",
      airport: "Heathrow Airport",
      code: "LHR",
      time: "20:00",
      date: "2024-04-15",
    },
    duration: "7h 00m",
    price: { economy: 450, business: 1200, firstClass: 2500 },
    seatsAvailable: { economy: 120, business: 30, firstClass: 8 },
    status: "scheduled",
  },
  {
    id: "flight-2",
    flightNumber: "SL-202",
    airline: "SkyLine Airways",
    departure: {
      city: "Los Angeles",
      airport: "Los Angeles International",
      code: "LAX",
      time: "10:30",
      date: "2024-04-16",
    },
    arrival: {
      city: "Tokyo",
      airport: "Narita International",
      code: "NRT",
      time: "15:30",
      date: "2024-04-17",
    },
    duration: "11h 00m",
    price: { economy: 680, business: 1800, firstClass: 3500 },
    seatsAvailable: { economy: 85, business: 22, firstClass: 6 },
    status: "scheduled",
    discount: 15,
    isPromotion: true,
  },
  {
    id: "flight-3",
    flightNumber: "SL-303",
    airline: "SkyLine Airways",
    departure: {
      city: "Paris",
      airport: "Charles de Gaulle",
      code: "CDG",
      time: "14:00",
      date: "2024-04-17",
    },
    arrival: {
      city: "Dubai",
      airport: "Dubai International",
      code: "DXB",
      time: "22:30",
      date: "2024-04-17",
    },
    duration: "6h 30m",
    price: { economy: 380, business: 950, firstClass: 2000 },
    seatsAvailable: { economy: 150, business: 35, firstClass: 10 },
    status: "scheduled",
  },
  {
    id: "flight-4",
    flightNumber: "SL-404",
    airline: "SkyLine Airways",
    departure: {
      city: "Singapore",
      airport: "Changi Airport",
      code: "SIN",
      time: "23:45",
      date: "2024-04-18",
    },
    arrival: {
      city: "Sydney",
      airport: "Sydney Airport",
      code: "SYD",
      time: "09:45",
      date: "2024-04-19",
    },
    duration: "8h 00m",
    price: { economy: 520, business: 1400, firstClass: 2800 },
    seatsAvailable: { economy: 95, business: 25, firstClass: 5 },
    status: "scheduled",
    discount: 20,
    isPromotion: true,
  },
  {
    id: "flight-5",
    flightNumber: "SL-505",
    airline: "SkyLine Airways",
    departure: {
      city: "London",
      airport: "Heathrow Airport",
      code: "LHR",
      time: "06:00",
      date: "2024-04-19",
    },
    arrival: {
      city: "New York",
      airport: "John F. Kennedy International",
      code: "JFK",
      time: "09:00",
      date: "2024-04-19",
    },
    duration: "8h 00m",
    price: { economy: 480, business: 1250, firstClass: 2600 },
    seatsAvailable: { economy: 110, business: 28, firstClass: 7 },
    status: "scheduled",
  },
];

// Mock Tickets
export const mockTickets: Ticket[] = [
  {
    id: "ticket-1",
    bookingRef: "SL-BK-001234",
    userId: "user-1",
    flightId: "flight-1",
    flight: mockFlights[0],
    passengerName: "John Smith",
    passengerEmail: "john@example.com",
    ticketClass: "economy",
    seatNumber: "24A",
    price: 450,
    baggage: { cabin: 1, checked: 1 },
    status: "confirmed",
    bookedAt: "2024-03-20",
  },
  {
    id: "ticket-2",
    bookingRef: "SL-BK-001235",
    userId: "user-1",
    flightId: "flight-2",
    flight: mockFlights[1],
    passengerName: "John Smith",
    passengerEmail: "john@example.com",
    ticketClass: "business",
    seatNumber: "5C",
    price: 1530,
    baggage: { cabin: 2, checked: 2 },
    status: "confirmed",
    bookedAt: "2024-03-22",
  },
  {
    id: "ticket-3",
    bookingRef: "SL-BK-001236",
    userId: "user-4",
    flightId: "flight-3",
    flight: mockFlights[2],
    passengerName: "Emma Wilson",
    passengerEmail: "emma@example.com",
    ticketClass: "firstClass",
    seatNumber: "1A",
    price: 2000,
    baggage: { cabin: 2, checked: 3 },
    status: "pending",
    bookedAt: "2024-03-25",
  },
];

// Mock Approval Requests
export const mockApprovalRequests: ApprovalRequest[] = [
  {
    id: "approval-1",
    type: "cancellation",
    requesterId: "user-1",
    requesterName: "John Smith",
    requesterEmail: "john@example.com",
    requesterRole: "customer",
    description:
      "Request to cancel booking SL-BK-001234 due to change of travel plans. Requesting full refund.",
    data: {
      ticketId: "ticket-1",
      bookingRef: "SL-BK-001234",
      reason: "Change of travel plans",
      refundAmount: 405,
    },
    status: "pending",
    createdAt: "2024-03-28",
  },
  {
    id: "approval-2",
    type: "promotion",
    requesterId: "user-2",
    requesterName: "Sarah Johnson",
    requesterEmail: "sarah@skyline.com",
    requesterRole: "employee",
    description:
      "Requesting 25% discount promotion for flight SL-505 (LHR-JFK) due to low booking rate at 40% capacity.",
    data: {
      flightId: "flight-5",
      flightNumber: "SL-505",
      discount: 25,
      reason: "Low booking rate - 40% capacity",
    },
    status: "pending",
    createdAt: "2024-03-27",
  },
  {
    id: "approval-3",
    type: "profile_edit",
    requesterId: "user-2",
    requesterName: "Sarah Johnson",
    requesterEmail: "sarah@skyline.com",
    requesterRole: "employee",
    description:
      "Request to update phone number from +1 234 567 8901 to +1 234 999 8888.",
    data: {
      field: "phone",
      oldValue: "+1 234 567 8901",
      newValue: "+1 234 999 8888",
    },
    status: "pending",
    createdAt: "2024-03-26",
  },
  {
    id: "approval-4",
    type: "cancellation",
    requesterId: "user-4",
    requesterName: "Emma Wilson",
    requesterEmail: "emma@example.com",
    requesterRole: "customer",
    description:
      "Request to cancel first class ticket for flight SL-303 due to medical emergency.",
    data: {
      ticketId: "ticket-3",
      bookingRef: "SL-BK-001236",
      reason: "Medical emergency",
      refundAmount: 1800,
    },
    status: "pending",
    createdAt: "2024-03-29",
  },
  {
    id: "approval-5",
    type: "profile_edit",
    requesterId: "user-5",
    requesterName: "David Brown",
    requesterEmail: "david@skyline.com",
    requesterRole: "employee",
    description:
      "Request to update email address from david@skyline.com to davidb@skyline.com.",
    data: {
      field: "email",
      oldValue: "david@skyline.com",
      newValue: "davidb@skyline.com",
    },
    status: "pending",
    createdAt: "2024-03-25",
  },
];

// Mock Destinations for Landing Page
export const mockDestinations: Destination[] = [
  {
    id: "dest-1",
    city: "Ho Chi Minh City",
    country: "Vietnam",
    image: "/HCM.jpg",
    description: "The city of lights",
    startingPrice: 2000000,
  },
  {
    id: "dest-2",
    city: "Da Nang",
    country: "Vietnam",
    image: "/danang.jpg",
    description: "Where tradition meets innovation",
    startingPrice: 3000000,
  },
  {
    id: "dest-3",
    city: "Bangkok",
    country: "Thailand",
    image: "/Bangkok.jpg",
    description: "Luxury in the desert",
    startingPrice: 4500000,
  },
  {
    id: "dest-4",
    city: "Ha Noi",
    country: "Vietnam",
    image: "/Hanoi.jpg",
    description: "Historic capital city",
    startingPrice: 2500000,
  },
  {
    id: "dest-5",
    city: "Hoi An",
    country: "Vietnam",
    image: "/Hoian.jpg",
    description: "Historic charm and modern culture",
    startingPrice: 3500000,
  },
  {
    id: "dest-6",
    city: "Phu Quoc",
    country: "Vietnam",
    image: "/phuquoc.jpg",
    description: "The city that never sleeps",
    startingPrice: 4000000,
  },
];

// Mock Revenue Data for Statistics
export const mockRevenueData: RevenueData[] = [
  { date: "2024-01", revenue: 125000, bookings: 245 },
  { date: "2024-02", revenue: 142000, bookings: 278 },
  { date: "2024-03", revenue: 168000, bookings: 312 },
  { date: "2024-04", revenue: 189000, bookings: 356 },
  { date: "2024-05", revenue: 210000, bookings: 398 },
  { date: "2024-06", revenue: 235000, bookings: 425 },
];

// Mock Flight Popularity for Statistics
export const mockFlightPopularity: FlightPopularity[] = [
  {
    flightId: "flight-1",
    flightNumber: "SL-101",
    route: "JFK - LHR",
    bookings: 156,
    revenue: 78000,
    occupancyRate: 85,
  },
  {
    flightId: "flight-2",
    flightNumber: "SL-202",
    route: "LAX - NRT",
    bookings: 98,
    revenue: 82000,
    occupancyRate: 72,
  },
  {
    flightId: "flight-3",
    flightNumber: "SL-303",
    route: "CDG - DXB",
    bookings: 134,
    revenue: 58000,
    occupancyRate: 68,
  },
  {
    flightId: "flight-4",
    flightNumber: "SL-404",
    route: "SIN - SYD",
    bookings: 112,
    revenue: 67000,
    occupancyRate: 78,
  },
  {
    flightId: "flight-5",
    flightNumber: "SL-505",
    route: "LHR - JFK",
    bookings: 89,
    revenue: 52000,
    occupancyRate: 45,
  },
];

// Current logged-in user (for demo purposes)
export const currentUser: User = mockUsers[0]; // Default to customer
